### ISSUE TITLE
Transaction information is missing in TracesSampler

### ISSUE THREAD

**Issue by ywilkof** [johnbellone/grpc-middleware-sentry#7]
When supplying a `TracesSampler` in `sentry.ClientOptions` there is an ability to supply a[ custom sampling function](https://docs.sentry.io/platforms/go/performance/#configure-the-sample-rate). 

A common pattern is to sample different endpoints with different propabilities of sampling. For example, we would like to never sample health endpoints. Another example is that there are high volume endpoint and low volume transactions which we would like to sample less frequently and more frequently respectively.

This is achieved usually using the transaction property of the current trace. However, due to the calling order in the Go implementation, the sampling function is called before the middleware sets the transaction on the trace. That prevents us from using the transaction as a deciding factor for sampling.

If we could bump up the `hub.Scope().SetTransaction(info.FullMethod)` in https://github.com/johnbellone/grpc-middleware-sentry/blob/master/server_interceptors.go#L51 then it should be possible.

**Comment by GTB3NW** [comment]
Okay, so after testing my PR it still doesn't get passed to the sampler. This line is the problem - https://github.com/getsentry/sentry-go/blob/master/tracing.go#L296

So it's hitting the `parent` sample decision because `type spanContextKey struct{}` is set on the context with the parent span pointer. On the server side it constructs a new span using `ContinueFromGrpcMetadata` to pull out the trace and span id, it then sets the parent span ID and **crucially** it doesn't set the parent span pointer (since it's a remote system).

Now, I'd like to replicate this for the client, I think it's fairly low risk to do since it's pretty much just replicating the server side logic which works pretty flawlessly.

However I'm tempted to PR sentry-go to add a helper to do it, that way it can be maintained. What's your thoughts on this? @ywilkof @johnbellone

**Comment by GTB3NW** [comment]
I've PR'd over here - https://github.com/getsentry/sentry-go/pull/450

You can see the release I'd like to PR for this project here - https://github.com/GalaxiteMC/grpc-middleware-sentry/releases/tag/v0.2.2

I'm currently testing this :)

**Comment by jtag05** [comment]
@GTB3NW mind sharing how you resolved this issue without your PR changes?

**Comment by GTB3NW** [comment]
> @GTB3NW mind sharing how you resolved this issue without your PR changes?

I didn't unfortunately. It's no longer something I'm working on

**Comment by johnbellone** [comment]
@GTB3NW is that fork of yours ready to merge?

**Comment by GTB3NW** [comment]
> @GTB3NW is that fork of yours ready to merge?

It's not. The sentry Devs weren't that responsive to the idea of multiple transactions reusing a context, nevermind the hacky way I tried to do it.
I tried but to no avail sorry!

**Comment by johnbellone** [comment]
Is this the point of `[SetDynamicSamplingContext](https://github.com/getsentry/sentry-go/blob/master/tracing.go#L332)` on the scope?

**Comment by GTB3NW** [comment]
> Is this the point of [the `SetDynamicSamplingContext` method](https://github.com/getsentry/sentry-go/blob/master/tracing.go#L332) on the scope?

Hey, sorry I'm unsure if this would be suitable. I've honestly got out the mindset of the go sentry sdk and its quirks so I can't confidently provide you an answer
